/**
 * SpiNNaker network_tester kernel.
 */

#ifndef NETWORK_TESTER_H
#define NETWORK_TESTER_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifndef MIN
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#endif

#ifndef MAX
#define MAX(a, b) (((a) < (b)) ? (b) : (a))
#endif

/**
 * The granularity of all time related measurements in microseconds.
 */
#define TIME_GRANULARITY_USEC 100

/**
 * Available types of traffic generator.
 */
typedef enum traffic_node_type {
	TN_BERNOULLI = 0,
	TN_RELAY = 1,
} traffic_node_type_t;


/**
 * Information logged about the recipt of packets.
 */
typedef struct traffic_node_source {
	/**
	 * The routing key to use for traffic generated by this node with sequence
	 * number bits set to zero.
	 */
	uint32_t key;
	
	/**
	 * Number of packets received without a payload.
	 */
	uint32_t num_received;
	
	/**
	 * Of the above counts, how many packets arrived out of order.
	 */
	uint32_t num_out_of_order;
	
	/**
	 * The last sequence number of an arriving packet. Used to count the number of
	 * out-of-order requests.
	 */
	uint32_t last_seq_num;
} traffic_node_source_t;


/**
 * Information globally applicable to a traffic node (i.e. traffic
 * generator/consumers).
 */
typedef struct traffic_node_spec {
	/**
	 * The type of traffic to generate.
	 */
	traffic_node_type_t type;
	
	/**
	 * The routing key to use for traffic generated by this node with sequence
	 * number bits set to zero.
	 */
	uint32_t key;
	
	/**
	 * Should generated packets include a payload.
	 */
	bool payload;
	
	/**
	 * Number of packets sent in total.
	 */
	uint32_t num_sent;
	
	/**
	 * Number of different sources of packets to be sunk by this trafic node.
	 */
	size_t num_sources;
	
	/**
	 * An array of num_sources, sorted in ascending key order, where recieved
	 * packet information is logged.
	 */
	traffic_node_source_t *sources;
	
	/**
	 * The data associated with each type of traffic node.
	 */
	union {
		/**
		 * When type=TN_BERNOULLI, this contains the parameters to a Bernoulli
		 * traffic model.
		 */
		struct {
			// Probability of a packet being sent each period. 0.0 - 1.0.
			double probability;
			
			// Number of microseconds between iterations of the traffic generator.
			uint32_t period;
		} bernoulli;
		
		/**
		 * When type=TN_RELAY, this contains the parameters to a relay
		 * traffic model.
		 */
		struct {
			// No parameters at present!
		} relay;
	} data;
} traffic_node_spec_t;


/**
 * Information globally applicable to a network node (i.e. core).
 */
typedef struct network_node_spec {
	/**
	 * A mask for bits of routing keys which hold the packet sequence number (must
	 * be a contiguous block from bit 0 onwards).
	 */
	uint32_t key_seq_mask;
	
	/**
	 * Number of microseconts to run the experiment for.
	 */
	uint32_t duration;
	
	/**
	 * The number of traffic nodes this network node implements.
	 */
	size_t num_traffic_nodes;
	
	/**
	 * An array of pointers to num_traffic_nodes traffic node descriptions.
	 */
	traffic_node_spec_t **traffic_nodes;
} network_node_spec_t;


/**
 * Generate and send a packet on behalf of the specified traffic source.
 */
void send_packet(network_node_spec_t *network_node,
                 traffic_node_spec_t *traffic_node);


/**
 * Get the timer tick interval which would best suit the set of Bernoulli
 * traffic nodes in this network node. If no such nodes are present, returns 0.
 */
uint get_bernoulli_tick_interval(network_node_spec_t *network_node);


/**
 * Run a single timestep of a Bernoulli traffic node.
 */
void bernoulli_tick(network_node_spec_t *network_node,
                    traffic_node_spec_t *traffic_node);


#endif
