sudo: false
language: python
python:
        - 2.7
        - 3.4
install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install python-coveralls
script: py.test network_tester --cov network_tester --durations=10
after_success:
        - coveralls
notifications:
        email: false
